#!/bin/bash
# ============================================================================
# Vanta installer — mirrors how Hermes/OpenClaw install.
# Builds the kernel + agent deps, seeds the ~/.vanta home, and installs a global
# `vanta` command into ~/.local/bin so you can start it from anywhere by typing
# `vanta`. Re-run any time (idempotent).
# ============================================================================
set -e

GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; NC='\033[0m'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo ""
echo -e "${CYAN}⚓ Vanta install${NC}"
echo ""

# --- prerequisites ----------------------------------------------------------
command -v cargo >/dev/null 2>&1 || { echo -e "${RED}✗${NC} Rust not found — https://rustup.rs"; exit 1; }
command -v node  >/dev/null 2>&1 || { echo -e "${RED}✗${NC} Node.js (22+) not found — https://nodejs.org"; exit 1; }

# --- build kernel + install deps (first run only) ---------------------------
if [ ! -x "$SCRIPT_DIR/target/debug/vanta-kernel" ]; then
  echo -e "${CYAN}→${NC} building the Rust safety kernel (first run)…"
  cargo build
fi
if [ ! -d "$SCRIPT_DIR/vanta-ts/node_modules" ]; then
  echo -e "${CYAN}→${NC} installing agent dependencies (first run)…"
  (cd "$SCRIPT_DIR/vanta-ts" && npm install)
fi
echo -e "${GREEN}✓${NC} kernel + deps ready"

# --- global `vanta` command → ~/.local/bin -----------------------------------
# A launcher (not a symlink) so run.sh resolves the repo from its real location.
BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/vanta" <<LAUNCHER
#!/bin/sh
# Vanta global launcher — generated by install.sh. Re-run install.sh if the repo moves.
exec "$SCRIPT_DIR/run.sh" "\$@"
LAUNCHER
chmod +x "$BIN_DIR/vanta"
echo -e "${GREEN}✓${NC} installed: vanta → $BIN_DIR/vanta"

# --- ensure ~/.local/bin is on PATH (only edits a shell rc if it isn't) ------
case ":$PATH:" in
  *":$BIN_DIR:"*)
    echo -e "${GREEN}✓${NC} $BIN_DIR already on PATH"
    ;;
  *)
    RC="$HOME/.zshrc"
    [[ "$SHELL" == *bash* ]] && RC="$HOME/.bashrc"
    if ! grep -q '\.local/bin' "$RC" 2>/dev/null; then
      printf '\n# Vanta — global command\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$RC"
      echo -e "${GREEN}✓${NC} added $BIN_DIR to PATH in $RC"
      echo -e "${YELLOW}→${NC} run: source $RC   (or open a new terminal)"
    fi
    ;;
esac

# --- seed the bundled skill library into ~/.vanta/skills ----------------------
if "$SCRIPT_DIR/run.sh" skills install >/dev/null 2>&1; then
  echo -e "${GREEN}✓${NC} bundled skills seeded into ~/.vanta/skills"
fi

# --- dev: install git pre-commit hook (gitleaks secret scan) -----------------
if [ -d "$SCRIPT_DIR/.git" ] && [ -f "$SCRIPT_DIR/scripts/pre-commit" ]; then
  ln -sf ../../scripts/pre-commit "$SCRIPT_DIR/.git/hooks/pre-commit" 2>/dev/null || true
  if command -v gitleaks &>/dev/null; then
    echo -e "${GREEN}✓${NC} pre-commit hook installed (gitleaks secret scan)"
  else
    echo -e "${YELLOW}⚠${NC}  pre-commit hook installed — install gitleaks for it to run: brew install gitleaks"
  fi
fi

echo ""
echo -e "${GREEN}✓ Done.${NC} Start with:"
echo "    vanta setup      # pick a model backend (ChatGPT / Claude / Gemini / local)"
echo "    vanta            # interactive session"
echo "    vanta doctor     # health check"
echo ""
