#!/bin/bash
# ============================================================================
# Argo installer — mirrors how Hermes/OpenClaw install.
# Builds the kernel + agent deps, seeds the ~/.argo home, and installs a global
# `argo` command into ~/.local/bin so you can start it from anywhere by typing
# `argo`. Re-run any time (idempotent).
# ============================================================================
set -e

GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; NC='\033[0m'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo ""
echo -e "${CYAN}⚓ Argo install${NC}"
echo ""

# --- prerequisites ----------------------------------------------------------
command -v cargo >/dev/null 2>&1 || { echo -e "${RED}✗${NC} Rust not found — https://rustup.rs"; exit 1; }
command -v node  >/dev/null 2>&1 || { echo -e "${RED}✗${NC} Node.js (22+) not found — https://nodejs.org"; exit 1; }

# --- build kernel + install deps (first run only) ---------------------------
if [ ! -x "$SCRIPT_DIR/target/debug/argo-kernel" ]; then
  echo -e "${CYAN}→${NC} building the Rust safety kernel (first run)…"
  cargo build
fi
if [ ! -d "$SCRIPT_DIR/argo-ts/node_modules" ]; then
  echo -e "${CYAN}→${NC} installing agent dependencies (first run)…"
  (cd "$SCRIPT_DIR/argo-ts" && npm install)
fi
echo -e "${GREEN}✓${NC} kernel + deps ready"

# --- global `argo` command → ~/.local/bin -----------------------------------
# A launcher (not a symlink) so run.sh resolves the repo from its real location.
BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/argo" <<LAUNCHER
#!/bin/sh
# Argo global launcher — generated by install.sh. Re-run install.sh if the repo moves.
exec "$SCRIPT_DIR/run.sh" "\$@"
LAUNCHER
chmod +x "$BIN_DIR/argo"
echo -e "${GREEN}✓${NC} installed: argo → $BIN_DIR/argo"

# --- ensure ~/.local/bin is on PATH (only edits a shell rc if it isn't) ------
case ":$PATH:" in
  *":$BIN_DIR:"*)
    echo -e "${GREEN}✓${NC} $BIN_DIR already on PATH"
    ;;
  *)
    RC="$HOME/.zshrc"
    [[ "$SHELL" == *bash* ]] && RC="$HOME/.bashrc"
    if ! grep -q '\.local/bin' "$RC" 2>/dev/null; then
      printf '\n# Argo — global command\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$RC"
      echo -e "${GREEN}✓${NC} added $BIN_DIR to PATH in $RC"
      echo -e "${YELLOW}→${NC} run: source $RC   (or open a new terminal)"
    fi
    ;;
esac

# --- seed the bundled skill library into ~/.argo/skills ----------------------
if "$SCRIPT_DIR/run.sh" skills install >/dev/null 2>&1; then
  echo -e "${GREEN}✓${NC} bundled skills seeded into ~/.argo/skills"
fi

echo ""
echo -e "${GREEN}✓ Done.${NC} Start with:"
echo "    argo setup      # pick a model backend (ChatGPT / Claude / Gemini / local)"
echo "    argo            # interactive session"
echo "    argo doctor     # health check"
echo ""
