#!/bin/bash
# ============================================================================
# Vanta installer.
# Builds the kernel + agent deps, seeds the ~/.vanta home, and installs a global
# `vanta` command into ~/.local/bin so you can start it from anywhere by typing
# `vanta`. Re-run any time (idempotent).
# ============================================================================
set -e

GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; NC='\033[0m'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo ""
echo -e "${CYAN}⚓ Vanta install${NC}"
echo ""

# --- prerequisites ----------------------------------------------------------
# Best-in-class one-command install: if a required tool is missing, offer to
# install it (Homebrew on macOS) instead of just failing. need <cmd> <brew> <url>.
need() {
  command -v "$1" >/dev/null 2>&1 && return 0
  echo -e "${YELLOW}⚠${NC}  $1 not found."
  if [ -n "$2" ] && command -v brew >/dev/null 2>&1; then
    printf "   Install %s with Homebrew now? [Y/n] " "$1"
    read -r ans </dev/tty 2>/dev/null || ans=n
    case "$ans" in [Nn]*) ;; *) brew install "$2" && command -v "$1" >/dev/null 2>&1 && return 0 ;; esac
  fi
  echo -e "${RED}✗${NC} $1 is required — install it: $3"; exit 1
}
need node node "https://nodejs.org"
need git git "https://git-scm.com/downloads"
need cargo "" "https://rustup.rs  (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh)"

# --- build kernel + install deps (first run only) ---------------------------
if [ ! -x "$SCRIPT_DIR/target/debug/vanta-kernel" ]; then
  echo -e "${CYAN}→${NC} building the Rust safety kernel (first run)…"
  cargo build
fi
if [ ! -d "$SCRIPT_DIR/vanta-ts/node_modules" ]; then
  echo -e "${CYAN}→${NC} installing agent dependencies (first run)…"
  # Users install runtime deps only (--omit=dev) — keeps the test toolchain (vitest/vite)
  # and its advisories off a tester's machine. tsx + typescript are runtime deps (the app
  # runs via tsx; the size gate / LSP use the TS compiler API), so they stay installed.
  (cd "$SCRIPT_DIR/vanta-ts" && npm install --omit=dev)
fi
echo -e "${GREEN}✓${NC} kernel + deps ready"

# --- global `vanta` command → ~/.local/bin -----------------------------------
# A SELF-LOCATING launcher (not a symlink, no baked-in path): it remembers where
# the repo is and, if the repo moves, finds it again by signature and updates the
# memo — so moving the repo never requires re-running install.sh.
BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/vanta" <<'LAUNCHER'
#!/bin/sh
# Vanta global launcher — generated by install.sh.
# Self-locating: VANTA_REPO override → remembered path → search by signature.
# Moving the repo does NOT require re-running install.sh.
VHOME="${VANTA_HOME:-$HOME/.vanta}"
STATE="$VHOME/repo-path"

# A valid Vanta checkout has run.sh + Cargo.toml + vanta-ts/package.json (the
# signature works even if the folder is renamed).
_vanta_valid() {
  [ -n "$1" ] && [ -x "$1/run.sh" ] && [ -f "$1/Cargo.toml" ] && [ -f "$1/vanta-ts/package.json" ]
}

REPO=""
if [ -n "$VANTA_REPO" ] && _vanta_valid "$VANTA_REPO"; then
  REPO="$VANTA_REPO"                                   # 1) explicit override
elif [ -f "$STATE" ] && _vanta_valid "$(cat "$STATE" 2>/dev/null)"; then
  REPO="$(cat "$STATE")"                               # 2) remembered (fast path)
else
  # 3) relocate: search likely roots for the Vanta signature (miss path only).
  for base in "$HOME/Documents/GitHub/_active" "$HOME/Documents/GitHub" \
              "$HOME/code" "$HOME/dev" "$HOME/projects" "$HOME/src" \
              "$HOME/Documents" "$HOME"; do
    [ -d "$base" ] || continue
    cand="$(find "$base" -maxdepth 3 \
              \( -name node_modules -o -name .git -o -name target \) -prune -o \
              -type f -name run.sh -print 2>/dev/null \
            | while IFS= read -r rs; do
                d="$(dirname "$rs")"
                if [ -f "$d/Cargo.toml" ] && [ -f "$d/vanta-ts/package.json" ]; then
                  echo "$d"; break
                fi
              done)"
    if [ -n "$cand" ]; then REPO="$cand"; break; fi
  done
fi

if ! _vanta_valid "$REPO"; then
  echo "vanta: could not locate the Vanta repo." >&2
  echo "  Move it back, set VANTA_REPO=/path/to/Vanta, or re-run install.sh." >&2
  exit 1
fi

mkdir -p "$VHOME" 2>/dev/null || true                  # remember for next time
printf '%s\n' "$REPO" > "$STATE" 2>/dev/null || true
exec "$REPO/run.sh" "$@"
LAUNCHER
chmod +x "$BIN_DIR/vanta"
mkdir -p "${VANTA_HOME:-$HOME/.vanta}" 2>/dev/null || true
printf '%s\n' "$SCRIPT_DIR" > "${VANTA_HOME:-$HOME/.vanta}/repo-path" 2>/dev/null || true
echo -e "${GREEN}✓${NC} installed: vanta → $BIN_DIR/vanta (self-locating)"

# --- ensure ~/.local/bin is on PATH (only edits a shell rc if it isn't) ------
case ":$PATH:" in
  *":$BIN_DIR:"*)
    echo -e "${GREEN}✓${NC} $BIN_DIR already on PATH"
    ;;
  *)
    RC="$HOME/.zshrc"
    [[ "$SHELL" == *bash* ]] && RC="$HOME/.bashrc"
    if ! grep -q '\.local/bin' "$RC" 2>/dev/null; then
      printf '\n# Vanta — global command\nexport PATH="$HOME/.local/bin:$PATH"\n' >> "$RC"
      echo -e "${GREEN}✓${NC} added $BIN_DIR to PATH in $RC"
      echo -e "${YELLOW}→${NC} run: source $RC   (or open a new terminal)"
    fi
    ;;
esac

# --- seed the bundled skill library into ~/.vanta/skills ----------------------
if "$SCRIPT_DIR/run.sh" skills install >/dev/null 2>&1; then
  echo -e "${GREEN}✓${NC} bundled skills seeded into ~/.vanta/skills"
fi

# --- dev: install git pre-commit hook (gitleaks secret scan) -----------------
if [ -d "$SCRIPT_DIR/.git" ] && [ -f "$SCRIPT_DIR/scripts/pre-commit" ]; then
  ln -sf ../../scripts/pre-commit "$SCRIPT_DIR/.git/hooks/pre-commit" 2>/dev/null || true
  if command -v gitleaks &>/dev/null; then
    echo -e "${GREEN}✓${NC} pre-commit hook installed (gitleaks secret scan)"
  else
    echo -e "${YELLOW}⚠${NC}  pre-commit hook installed — install gitleaks for it to run: brew install gitleaks"
  fi
fi

echo ""
echo -e "${GREEN}✓ Done.${NC} Start with:"
echo "    vanta setup      # pick a model backend (ChatGPT / Claude / Gemini / local)"
echo "    vanta            # interactive session"
echo "    vanta doctor     # health check"
echo "    vanta preflight  # check optional deps for voice / desktop / swarm"
echo ""
