import { createHash } from "node:crypto";
import { Script } from "node:vm";
import { mkdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { z } from "zod";
import { GroundedStateSchema, type GroundedState } from "./grounding.js";
import {
  executeTaskModel,
  type ModelSandboxReceipt,
  type ModelSandboxStatus,
} from "./model-sandbox.js";

const SourceTransitionSchema = z.object({
  runId: z.string().min(1),
  sequence: z.number().int().positive(),
});

export const TaskModelManifestSchema = z.object({
  schemaVersion: z.literal(1),
  taskId: z.string().regex(/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,127}$/),
  modelVersion: z.number().int().positive(),
  representationVersion: z.number().int().positive(),
  createdAt: z.string().datetime(),
  sourceHash: z.string().regex(/^[a-f0-9]{64}$/),
  sourceTransitions: z.array(SourceTransitionSchema).min(1),
});

const ActivePointerSchema = z.object({
  schemaVersion: z.literal(1),
  taskId: TaskModelManifestSchema.shape.taskId,
  modelVersion: z.number().int().positive(),
});

export type TaskModelManifest = z.infer<typeof TaskModelManifestSchema>;
export type TaskModelArtifact = {
  manifest: TaskModelManifest;
  source: string;
  generatedTypes: string;
};
export type TaskModelErrorCode =
  | "invalid_manifest"
  | "invalid_source"
  | "semantic_invalid"
  | "sandbox_failed"
  | "version_conflict";
export type TaskModelError = { code: TaskModelErrorCode; message: string };
export type InstallTaskModelOptions = {
  root: string;
  taskId: string;
  modelVersion: number;
  source: string;
  state: GroundedState;
  action: unknown;
  timeline: readonly unknown[];
  sourceTransitions: Array<{ runId: string; sequence: number }>;
  createdAt?: string;
  recordReceipt(receipt: ModelSandboxReceipt): Promise<void>;
};
export type InstallTaskModelResult =
  | { ok: true; artifact: TaskModelArtifact; predicted: GroundedState; goal: boolean; receipt: ModelSandboxReceipt }
  | { ok: false; error: TaskModelError; receipt?: ModelSandboxReceipt };

function failure(code: TaskModelErrorCode, message: string, receipt?: ModelSandboxReceipt): InstallTaskModelResult {
  return { ok: false, error: { code, message }, ...(receipt ? { receipt } : {}) };
}

function modelDirectory(root: string, taskId: string, version: number): string {
  return join(root, taskId, "versions", String(version).padStart(4, "0"));
}

function typeUnion(values: string[]): string {
  return values.length ? values.map((value) => JSON.stringify(value)).join(" | ") : "never";
}

export function generateTaskModelTypes(state: GroundedState): string {
  const entityIds = state.entities.map((entity) => entity.id).sort();
  const counterKeys = Object.keys(state.counters).sort();
  return [
    "// Generated by Vanta. Do not edit this version in place.",
    `export type EntityId = ${typeUnion(entityIds)};`,
    `export type CounterKey = ${typeUnion(counterKeys)};`,
    "export type ModelState = {",
    "  readonly schemaVersion: 1;",
    `  readonly representationVersion: ${state.representationVersion};`,
    "  readonly entities: ReadonlyArray<{ readonly id: EntityId; readonly [key: string]: unknown }> ;",
    "  readonly counters: Readonly<Record<CounterKey, { readonly value: unknown; readonly [key: string]: unknown }>>;",
    "  readonly [key: string]: unknown;",
    "};",
    "export type TaskModelInput = { readonly state: ModelState; readonly action: unknown; readonly timeline: readonly unknown[] };",
    "export type TaskModel = { step(input: TaskModelInput): ModelState; isGoal(state: ModelState): boolean };",
    "",
  ].join("\n");
}

function compileSource(source: string): string | undefined {
  try {
    new Script(`(${source})`, { filename: "task-model.js" });
    return undefined;
  } catch (error) {
    return error instanceof Error ? error.message : String(error);
  }
}

function sandboxFailure(status: ModelSandboxStatus): TaskModelErrorCode {
  return status === "runtime_error" || status === "nondeterministic" ? "semantic_invalid" : "sandbox_failed";
}

async function pathExists(path: string): Promise<boolean> {
  try { await stat(path); return true; } catch { return false; }
}

async function persistArtifact(root: string, artifact: TaskModelArtifact): Promise<TaskModelError | undefined> {
  const { taskId, modelVersion } = artifact.manifest;
  const taskRoot = join(root, taskId);
  const versionRoot = modelDirectory(root, taskId, modelVersion);
  await mkdir(join(taskRoot, "versions"), { recursive: true });
  if (await pathExists(versionRoot)) return { code: "version_conflict", message: `task model version ${modelVersion} already exists` };
  await mkdir(versionRoot);
  try {
    await Promise.all([
      writeFile(join(versionRoot, "manifest.json"), `${JSON.stringify(artifact.manifest, null, 2)}\n`, { encoding: "utf8", flag: "wx" }),
      writeFile(join(versionRoot, "model.js"), `${artifact.source.trim()}\n`, { encoding: "utf8", flag: "wx" }),
      writeFile(join(versionRoot, "types.d.ts"), artifact.generatedTypes, { encoding: "utf8", flag: "wx" }),
    ]);
    const pointer = `${JSON.stringify({ schemaVersion: 1, taskId, modelVersion }, null, 2)}\n`;
    const temporary = join(taskRoot, `.active-${process.pid}-${Date.now()}.json`);
    await writeFile(temporary, pointer, { encoding: "utf8", flag: "wx" });
    await rename(temporary, join(taskRoot, "active.json"));
  } catch (error) {
    await rm(versionRoot, { recursive: true, force: true });
    throw error;
  }
  return undefined;
}

export async function installTaskModel(options: InstallTaskModelOptions): Promise<InstallTaskModelResult> {
  const state = GroundedStateSchema.safeParse(options.state);
  const source = options.source.trim();
  const sourceHash = createHash("sha256").update(source).digest("hex");
  const manifest = TaskModelManifestSchema.safeParse({
    schemaVersion: 1,
    taskId: options.taskId,
    modelVersion: options.modelVersion,
    representationVersion: options.state.representationVersion,
    createdAt: options.createdAt ?? new Date().toISOString(),
    sourceHash,
    sourceTransitions: options.sourceTransitions,
  });
  if (!state.success || !manifest.success) return failure("invalid_manifest", "task model metadata or grounded state is invalid");
  const ownsGroundedSource = manifest.data.sourceTransitions.some((transition) => (
    transition.runId === state.data.source.runId && transition.sequence === state.data.source.transitionSequence
  ));
  if (!ownsGroundedSource) return failure("invalid_manifest", "source lineage must include the grounded state's transition");
  const compileError = compileSource(source);
  if (compileError) return failure("invalid_source", compileError);
  if (await pathExists(modelDirectory(options.root, options.taskId, options.modelVersion))) {
    return failure("version_conflict", `task model version ${options.modelVersion} already exists`);
  }

  const executed = await executeTaskModel({
    source,
    input: { state: state.data, action: options.action, timeline: options.timeline },
    recordReceipt: options.recordReceipt,
  });
  if (!executed.ok) return failure(sandboxFailure(executed.receipt.status), executed.error, executed.receipt);
  const predicted = GroundedStateSchema.safeParse(executed.predicted);
  if (!predicted.success || predicted.data.representationVersion !== state.data.representationVersion) {
    return failure("semantic_invalid", "step() must return a GroundedState with the active representation version", executed.receipt);
  }
  const artifact = {
    manifest: manifest.data,
    source,
    generatedTypes: generateTaskModelTypes(state.data),
  } satisfies TaskModelArtifact;
  const persistenceError = await persistArtifact(options.root, artifact);
  if (persistenceError) return { ok: false, error: persistenceError, receipt: executed.receipt };
  return { ok: true, artifact, predicted: predicted.data, goal: executed.goal, receipt: executed.receipt };
}

export async function inspectTaskModelVersion(root: string, taskId: string, version: number): Promise<TaskModelArtifact | undefined> {
  try {
    if (!TaskModelManifestSchema.shape.taskId.safeParse(taskId).success) return undefined;
    const directory = modelDirectory(root, taskId, version);
    const [manifestJson, source, generatedTypes] = await Promise.all([
      readFile(join(directory, "manifest.json"), "utf8"),
      readFile(join(directory, "model.js"), "utf8"),
      readFile(join(directory, "types.d.ts"), "utf8"),
    ]);
    const manifest = TaskModelManifestSchema.parse(JSON.parse(manifestJson));
    const actualHash = createHash("sha256").update(source.trim()).digest("hex");
    if (manifest.taskId !== taskId || manifest.modelVersion !== version || manifest.sourceHash !== actualHash) return undefined;
    return { manifest, source, generatedTypes };
  } catch {
    return undefined;
  }
}

export async function inspectActiveTaskModel(root: string, taskId: string): Promise<TaskModelArtifact | undefined> {
  try {
    if (!TaskModelManifestSchema.shape.taskId.safeParse(taskId).success) return undefined;
    const pointer = ActivePointerSchema.parse(JSON.parse(await readFile(join(root, taskId, "active.json"), "utf8")));
    if (pointer.taskId !== taskId) return undefined;
    return inspectTaskModelVersion(root, taskId, pointer.modelVersion);
  } catch {
    return undefined;
  }
}

export async function diffTaskModelVersions(root: string, taskId: string, from: number, to: number): Promise<{
  sourceChanged: boolean;
  generatedTypesChanged: boolean;
  changedSourceLines: number[];
  addedSourceTransitions: string[];
}> {
  const [before, after] = await Promise.all([
    inspectTaskModelVersion(root, taskId, from),
    inspectTaskModelVersion(root, taskId, to),
  ]);
  if (!before || !after) throw new Error("task model version not found");
  const priorLines = before.source.split("\n");
  const nextLines = after.source.split("\n");
  const changedSourceLines = Array.from({ length: Math.max(priorLines.length, nextLines.length) }, (_, index) => index)
    .filter((index) => priorLines[index] !== nextLines[index]).map((index) => index + 1);
  const priorTransitions = new Set(before.manifest.sourceTransitions.map((item) => `${item.runId}:${item.sequence}`));
  return {
    sourceChanged: before.manifest.sourceHash !== after.manifest.sourceHash,
    generatedTypesChanged: before.generatedTypes !== after.generatedTypes,
    changedSourceLines,
    addedSourceTransitions: after.manifest.sourceTransitions
      .map((item) => `${item.runId}:${item.sequence}`).filter((item) => !priorTransitions.has(item)),
  };
}
