// VANTA-UNDERCOVER-MODE — strips Vanta-INTERNAL provenance from generated text
// (commit messages, PR bodies) before it lands in a PUBLIC/OSS repo. This CLEANS
// internal bookkeeping — internal `.vanta/` paths, internal card-id tags, and
// "generated by Vanta"/internal-tooling provenance lines — it does NOT fabricate
// authorship. Off by default (VANTA_UNDERCOVER unset/!=1) = text byte-identical.
//
// Pure: no I/O, no throws. Intended consumers (wire in a follow-up, mirroring the
// clarity-gate seam): batch/batch.ts `buildGhPrArgs` (the PR `--body`) and any
// commit-message build site (the `git commit` helper). This round ships the
// stripper + tests only; nothing is wired into a shared host.

// Internal `.vanta/` path mentions: `.vanta/loops/x.json`, `~/.vanta/brain`, a
// bare `.vanta/`. Group 1 captures a leading delimiter (space/bracket/quote/`~/`)
// so it can be preserved while the path token is dropped.
const INTERNAL_PATH_RE = /(^|[\s([{`'"]|~\/)(?:\.\/)?\.vanta(?:\/[\w.\-/]*)?/g;

/** Internal bookkeeping card-id tags: `CC-1234`, `VANTA-FOO-CARD`, `VANTA-SOME-THING`. */
const CARD_ID_RE = /\b(?:CC-[A-Z0-9-]+|VANTA-[A-Z0-9-]+)\b/g;

/** A whole line is provenance if it announces internal-tooling authorship. */
const PROVENANCE_LINE_RE =
  /^\s*(?:[-*>#]+\s*)?(?:🤖\s*)?(?:generated|authored|created|made|produced|written|automated)\s+(?:with|by|using|via|through)\s+.*\bvanta\b.*$/i;

/** A `Co-Authored-By:`-style trailer that names Vanta internal tooling. */
const COAUTHOR_LINE_RE = /^\s*co-authored-by:\s*.*\bvanta\b.*$/i;

/** True when undercover mode is on (`VANTA_UNDERCOVER=1`). Default off. Pure. */
export function undercoverEnabled(env: NodeJS.ProcessEnv): boolean {
  return env.VANTA_UNDERCOVER === "1";
}

/** Drop a whole line if it is an internal-tooling provenance/co-author trailer. */
function isProvenanceLine(line: string): boolean {
  return PROVENANCE_LINE_RE.test(line) || COAUTHOR_LINE_RE.test(line);
}

/** Strip inline internal markers (paths + card-id tags) from one retained line. */
function stripInlineMarkers(line: string): string {
  return line
    .replace(INTERNAL_PATH_RE, (_m, lead: string) => (lead === "~/" ? "" : lead))
    .replace(CARD_ID_RE, "");
}

/** Collapse run-on spaces a strip left, trim trailing space, drop the empty parens/brackets a strip may leave. */
function tidyLine(line: string): string {
  return line
    .replace(/\(\s*\)|\[\s*\]/g, "")
    .replace(/[ \t]{2,}/g, " ")
    .replace(/[ \t]+([.,;:)\]])/g, "$1")
    .replace(/[ \t]+$/g, "");
}

/** Collapse 3+ blank lines (left by dropped provenance lines) to at most one. */
function tidyBlankRuns(lines: string[]): string[] {
  const out: string[] = [];
  let blanks = 0;
  for (const line of lines) {
    if (line.trim() === "") {
      blanks += 1;
      if (blanks <= 1) out.push("");
    } else {
      blanks = 0;
      out.push(line);
    }
  }
  while (out.length && out[out.length - 1] === "") out.pop();
  while (out.length && out[0] === "") out.shift();
  return out;
}

/**
 * Remove clearly-internal Vanta markers from text, leaving normal prose and real
 * code identifiers intact. Conservative: only `.vanta/` paths, `CC-`/`VANTA-`
 * card-id tags, and whole "generated by Vanta"/co-author provenance lines go.
 * Pure.
 */
export function stripInternalMarkers(text: string): string {
  const kept: string[] = [];
  for (const raw of text.split("\n")) {
    if (isProvenanceLine(raw)) continue;
    kept.push(tidyLine(stripInlineMarkers(raw)));
  }
  return tidyBlankRuns(kept).join("\n");
}

/** Strip internal markers when undercover is enabled, else return text unchanged. Pure. */
export function applyUndercover(text: string, env: NodeJS.ProcessEnv): string {
  return undercoverEnabled(env) ? stripInternalMarkers(text) : text;
}
