import { describe, expect, it } from "vitest";
import { applyUndercover, stripInternalMarkers, undercoverEnabled } from "./undercover.js";

describe("undercoverEnabled", () => {
  it("is true only when VANTA_UNDERCOVER=1", () => {
    expect(undercoverEnabled({ VANTA_UNDERCOVER: "1" })).toBe(true);
  });

  it("is false when unset (default off)", () => {
    expect(undercoverEnabled({})).toBe(false);
  });

  it("is false for any other value", () => {
    expect(undercoverEnabled({ VANTA_UNDERCOVER: "0" })).toBe(false);
    expect(undercoverEnabled({ VANTA_UNDERCOVER: "true" })).toBe(false);
    expect(undercoverEnabled({ VANTA_UNDERCOVER: "" })).toBe(false);
  });
});

describe("stripInternalMarkers — internal .vanta/ paths", () => {
  it("removes an inline .vanta/ path mention, tidying the empty parens it leaves", () => {
    expect(stripInternalMarkers("see (.vanta/loops/x.json) for state")).toBe("see for state");
  });

  it("removes a ~/.vanta path", () => {
    expect(stripInternalMarkers("token in ~/.vanta/brain/entries.json")).toBe("token in");
  });

  it("removes a bare .vanta/ token", () => {
    expect(stripInternalMarkers("wrote .vanta/handoff.md")).toBe("wrote");
  });

  it("keeps a quote delimiter that anchored the path", () => {
    expect(stripInternalMarkers('path is ".vanta/goals.tsv" here')).toBe('path is "" here');
  });
});

describe("stripInternalMarkers — internal card-id tags", () => {
  it("removes a CC-1234 bookkeeping tag", () => {
    expect(stripInternalMarkers("fix the parser CC-1234 today")).toBe("fix the parser today");
  });

  it("removes a VANTA-XXX-CARD style tag", () => {
    expect(stripInternalMarkers("ships VANTA-UNDERCOVER-MODE behind a flag")).toBe(
      "ships behind a flag",
    );
  });

  it("removes a card tag in parentheses, tidying the empty parens", () => {
    expect(stripInternalMarkers("done (CC-TODO)")).toBe("done");
  });
});

describe("stripInternalMarkers — provenance lines", () => {
  it("drops a 'Generated with Vanta' line", () => {
    const text = "Real change.\n\nGenerated with Vanta batch.";
    expect(stripInternalMarkers(text)).toBe("Real change.");
  });

  it("drops an 'Automated by vanta' provenance line", () => {
    const text = "Open PR for the fix.\nAutomated by `vanta batch` (worker w1).";
    expect(stripInternalMarkers(text)).toBe("Open PR for the fix.");
  });

  it("drops a 🤖 emoji-prefixed generated-by line", () => {
    const text = "Body text.\n\n🤖 Generated by Vanta";
    expect(stripInternalMarkers(text)).toBe("Body text.");
  });

  it("drops a Co-Authored-By Vanta trailer", () => {
    const text = "Subject line\n\nCo-Authored-By: Vanta <noreply@vanta>";
    expect(stripInternalMarkers(text)).toBe("Subject line");
  });
});

describe("stripInternalMarkers — leaves normal content intact", () => {
  it("does not touch normal prose", () => {
    const text = "Fix the off-by-one in the pagination cursor.";
    expect(stripInternalMarkers(text)).toBe(text);
  });

  it("does not touch a real code identifier resembling a path", () => {
    const text = "import { foo } from './config/vanta.js'";
    expect(stripInternalMarkers(text)).toBe(text);
  });

  it("does not strip the word vanta in normal prose (only path/tag/provenance)", () => {
    const text = "The vanta kernel gates every action.";
    expect(stripInternalMarkers(text)).toBe(text);
  });

  it("does not touch a non-internal hyphenated word", () => {
    const text = "Use ASCII-only output for the CI logs.";
    expect(stripInternalMarkers(text)).toBe(text);
  });
});

describe("stripInternalMarkers — whitespace tidying", () => {
  it("collapses 3+ blank lines a dropped provenance line leaves", () => {
    const text = "Line one.\n\n\nGenerated by Vanta\n\n\nLine two.";
    expect(stripInternalMarkers(text)).toBe("Line one.\n\nLine two.");
  });

  it("collapses run-on spaces and trims trailing space from a strip", () => {
    expect(stripInternalMarkers("done   CC-9 ")).toBe("done");
  });

  it("drops trailing blank lines", () => {
    expect(stripInternalMarkers("body\n\n")).toBe("body");
  });

  it("drops a leading blank a first-line provenance strip leaves", () => {
    expect(stripInternalMarkers("Generated by Vanta\n\nReal body.")).toBe("Real body.");
  });
});

describe("applyUndercover", () => {
  it("strips markers when enabled", () => {
    const text = "Fix parser CC-1234.";
    expect(applyUndercover(text, { VANTA_UNDERCOVER: "1" })).toBe("Fix parser.");
  });

  it("returns text byte-identical when off (default)", () => {
    const text = "Fix parser CC-1234 — see .vanta/goals.tsv.\nGenerated by Vanta";
    expect(applyUndercover(text, {})).toBe(text);
  });

  it("returns text byte-identical when explicitly disabled", () => {
    const text = "wrote .vanta/handoff.md VANTA-FOO-CARD";
    expect(applyUndercover(text, { VANTA_UNDERCOVER: "0" })).toBe(text);
  });
});
