const USAGE_LINES = [
      "Vanta — a local trusted operator. Knows the goal, gates every action, reports only verified output.",
      "The bar is finishing real tasks reliably and unattended, not feature count.",
      "",
      "Usage: vanta                              start an interactive session",
      "       vanta --effort <low|medium|high|max>   set model effort for this session",
      "       vanta home                         operator home: workflows, channels, tasks, memory, setup",
      "       vanta command-center               Life OS dashboards: today, money, projects, sales, learning, reflection",
      "       vanta what-can-i-do [--check|--fresh-workspace-check|--fresh-context-review|--demo <id>|--review-packet]   show workflows / proofs",
      "       vanta diagnose-crash [--demo greg-uitests|<file>|-]   diagnose crash/build logs with cited evidence",
      "       vanta spec-to-app --demo posture [--open]   build a verified React/Tailwind preview from a spec",
      "       vanta research-receipts <claims.json> [--vault <dir> --apply]   source/date/expiry skeptic gate",
      "       vanta intent extract <target> --out <spec.json> | intent check <target> <spec.json>",
      "       vanta auto-watch [list|run|add]   watch repos/issues/email/calendar via gated commands",
      "       vanta marketing read <amplitude|customerio> [--fixture <json>]   read marketing connector data",
      "       vanta ambient-screen [enable|disable|status|tick]   opt-in screen/app context proposals",
      "       vanta harness-thickness [--no-record] | harness-thickness remove <file:line> --expected <text>   audit/prune harness bloat",
      "       vanta kanban create <goal> | kanban swarm|status|digest [id]   decompose a goal into lanes + run/resume a local swarm",
      "       vanta lead \"<message>\" | lead list   turn lead-agent chat into tracked work objects",
      "       vanta deep-plan create|revise|approve|start   revisionable plan docs with approval gate",
      "       vanta runtime start --fleet <id> --worker <id> --port <n> --command <cmd>   start a preview bound to a fleet worktree",
      "       vanta backend [status|verify|gateway]   inspect, deploy, or live-prove the selected execution backend",
      "       vanta run-anywhere status|proof-packet [--json] [--check-release]   aggregate or package Modal/Teams/Termux proof readiness",
      "       vanta a2a autonomous-status [--json]   check Docker/image/auth/proof readiness for boxed autonomous builds",
      "       vanta adversarial-ux --fixture checkout | --url <url>   turn hard-user UX findings into tickets",
      "       vanta egress [status|plan]        show Docker/network egress isolation posture",
      "       vanta billing [status|json]      show fail-open provider billing + estimated spend",
      "       vanta osint plan <subject> [--domain <domain> --ticker <ticker>]   public-records investigation plan",
      "       vanta autonomy [show|init|pending|resolve|decide]   acts-alone / queues / wakes-me contract",
      "       vanta proactive [status|run|verify <loop-id>|silence <minutes|off>]   earn and use per-loop autonomy",
      "       vanta api serve [port] | api token [create|list|revoke]   versioned HTTP API + bearer tokens",
      "       vanta --init | --init-only | --maintenance   run lifecycle bootstrap hooks",
      "       vanta --plugin-url <url> | --plugin-dir <path>   install a plugin (.zip/dir) at startup (stays disabled until enabled)",
      "       vanta sessions | resume <id> [--fork-session]   list, resume, or fork a session",
      "       vanta setup                        complete guided wizard: model, messaging, MCP, personality, health",
      "       vanta setup model                  just the model/provider picker",
      "       vanta setup messaging              configure a messaging gateway (Telegram, …)",
      "       vanta setup tts                    configure the voice/TTS provider (Edge keyless, OpenAI, ElevenLabs, local)",
      "       vanta voice wake [on|off|status|listen]   opt-in local Hey Vanta listener",
      "       vanta config <get|set|edit|check>  manage settings (~/.vanta/config.json; secrets → .env)",
      "       vanta status | doctor              health check (kernel, provider, keys, store)",
      "       vanta keybindings [doctor|template [--force]|path]   manage ~/.vanta/keybindings.json",
      "       vanta goals                        show kernel goals plus dependency graph state",
      "       vanta goals sentinel [list|run|add|retire]   watch completed goals with cheap checks",
      '       vanta run "<instruction>"          run one instruction and exit',
      "       vanta skills [install [--force]|lint]   list / install bundled / validate SKILL.md files",
      '       vanta skill <name> ["<instruction>"]  print a skill, or run with it',
      '       vanta schedule "<instruction>" --cron "<expr>" | schedule list',
      "       vanta cron                         run due tasks once (for launchd/cron)",
      "       vanta gateway                      run the scheduler as a foreground daemon",
      "       vanta gateway verify-channels      log live/not-configured status for messaging adapters",
      "       vanta gateway channel-proofs [platform] [--json]  show accepted inbound-to-reply receipts",
      "       vanta service [install|uninstall|status]   manage the background launchd agent",
      "       vanta agents [list|logs|attach|stop|rm|respawn]   manage background agent sessions",
      "       vanta profiles [list|create|clone|switch|archive|target|inbox]   manage persistent specialist profiles",
      "       vanta hire <role> --adapter <id> [--budget <usd>]   add a budgeted, role-tagged agent to the roster",
      "       vanta heartbeat                    one coalesced wakeup: budget→workspace→secret→skill→adapter + orphan recovery",
      "       vanta fleet run --task <instruction> [--task <instruction> ...]   fan out worktree workers",
      "       vanta daemon [status|stop]          inspect or stop the background supervisor",
      "       vanta auto-mode [defaults|config]  inspect auto permission classifier config",
      "       vanta auto-research --objective <text> --metric <cmd> --bounds <text>   improve a numeric metric in worktrees",
      "       vanta eval mem formation [data-dir]   A/B ADD-only memory formation vs crystallization",
      "       vanta meta-tune instructions [--iters N] [--adopt]   score bounded PROGRAM.md variants",
      "       vanta trajectory export [--tools-only --limit N --out <dir>] | trajectory train <lora-sft.jsonl>   export/compress tool trajectories for local LoRA",
      "       vanta rooms | room <name> [\"<instruction>\"]   project rooms",
      "       vanta modes [list|install]         operator modes",
      "       vanta auth google [--client <json>] one-time Google OAuth (ingests client_secret.json)",
      "       vanta mcp [list|serve]             list MCP servers Vanta consumes, or serve Vanta's tools over MCP stdio",
      "       vanta roadmap                      build roadmap.html from roadmap.json and open it",
      "       vanta roadmap status [--json] [--open [--actionable]] [--require-drained|--require-complete]  print counts/open work; gates exit nonzero when unmet",
      "       vanta roadmap move <id> <status> [--force]   move an item (shipped|building|blocked|next|horizon|parked)",
      "       vanta roadmap unblock [id...] [--json]  show concrete unblock steps for blocked/parked/decision cards",
      "       vanta roadmap serve                start drag-and-drop board at http://localhost:7789/roadmap/board",
      "       vanta now [--apply]                propose/fill the next 1-2 Now cards without exceeding WIP",
      "       vanta desktop [port] [--companion]  start desktop; opt into token-paired LAN companion access",
      "       vanta audit                        npm + cargo dependency security scan",
      "       vanta lint [files|--staged]        code-size gate: file≤300 fn≤50 params≤4 complexity≤10",
      "       vanta model [list | <provider> [<model>]]  show or switch the active provider/model",
      "       vanta pairing [list | approve <chatId>]  manage messaging platform pairings",
      "       vanta update [--rollback]              pull latest + rebuild; --rollback restores last snapshot",
      "       vanta open <file[:line]>           open a file:line in your editor",
      "       vanta prompt-size                  per-turn token breakdown (prompt + tool schemas)",
      "       vanta completion [bash|zsh|fish]   print a shell completion script",
      "       vanta backup [out.tgz] | import <in.tgz>   archive / restore ~/.vanta",
      "       vanta improve                      run one factory cycle (review mode — prints plan)",
      "       vanta factory [approve|status]     execute or check the dark factory (autonomy L1-4 via VANTA_AUTONOMY_LEVEL)",
];

export function usage(): void {
  console.log(USAGE_LINES.join("\n"));
}

export function usageExit(): never {
  usage();
  process.exit(1);
}
