import type { Skill } from "./types.js";

// SKILL-TRIGGERS (Codex half) — Codex has NO event hooks, so a skill's prompt-level routing becomes
// a standing instruction in AGENTS.md (which Codex reads each session). PURE: skill → routing line,
// + an idempotent marked-block merge into an existing AGENTS.md so re-syncs never duplicate.

export const CODEX_BLOCK_START = "<!-- vanta:skill-triggers:start -->";
export const CODEX_BLOCK_END = "<!-- vanta:skill-triggers:end -->";
const HEADING = "## Skill routing (auto-generated by Vanta — do not edit inside this block)";

/** A skill's UserPromptSubmit triggers → one AGENTS.md routing line. Tool/Stop triggers are skipped:
 *  Codex can only act on prompt intent, not events. Returns null when there's no prompt-level trigger. */
export function compileTriggersForCodex(skill: Skill): string | null {
  const prompt = (skill.meta.triggers ?? []).filter((t) => t.event === "UserPromptSubmit");
  if (!prompt.length) return null;
  const cond = prompt.map((t) => (t.match ? `matches /${t.match}/` : "is relevant")).join(" or ");
  const desc = skill.meta.description ? ` (${skill.meta.description})` : "";
  return `- **${skill.meta.name}** — when the user's request ${cond}, apply this skill${desc}.`;
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Idempotently merge generated routing lines into AGENTS.md: replace the marked block, preserve
 *  everything else. Empty `lines` removes the block entirely. */
export function mergeAgentsMd(existing: string, lines: string[]): string {
  const re = new RegExp(`\\n*${escapeRe(CODEX_BLOCK_START)}[\\s\\S]*?${escapeRe(CODEX_BLOCK_END)}\\n*`, "g");
  const without = existing.replace(re, "\n").trimEnd();
  if (!lines.length) return without ? `${without}\n` : "";
  const block = [CODEX_BLOCK_START, HEADING, "", ...lines, "", CODEX_BLOCK_END].join("\n");
  return without ? `${without}\n\n${block}\n` : `${block}\n`;
}
