/** Canonical command catalog — drives `/help`, the TUI palette, and validation. */
export const SLASH_COMMANDS: ReadonlyArray<{ name: string; arg?: string; desc: string }> = [
  { name: "help", desc: "show this command list" },
  { name: "clear", desc: "start a fresh conversation (keeps the session log)" },
  { name: "reset", desc: "start a fresh conversation (alias of /clear)" },
  { name: "history", desc: "show this conversation's transcript" },
  { name: "export", desc: "export this conversation to a markdown file" },
  { name: "init", arg: "[--force|--print]", desc: "generate .claude/CLAUDE.md project context for future sessions" },
  { name: "init-verifiers", desc: "detect the project's build/test/lint/typecheck gates → verifier skills it can run to check its work" },
  { name: "stop", desc: "graceful soft-stop — finish the current tool call, then end the turn with a summary" },
  { name: "retry", desc: "re-run your last message" },
  { name: "undo", desc: "drop the last turn from the conversation" },
  { name: "rewind", arg: "[id]", desc: "list or restore recent per-edit file checkpoints" },
  { name: "hooks", arg: "[add|remove]", desc: "list, add, or remove shell hooks in .vanta/hooks.json" },
  { name: "model", desc: "change provider & model — interactive picker" },
  { name: "effort", arg: "<low|medium|high|max>", desc: "set model effort for this session" },
  { name: "env", arg: "[KEY=value|-KEY]", desc: "session-scoped env vars injected into shell_cmd/run_code child processes" },
  { name: "cd", arg: "[path]", desc: "change the session working directory for shell_cmd (no arg prints it)" },
  { name: "setup", desc: "configure the model backend — opens the provider/model picker" },
  { name: "tools", desc: "list available tools" },
  { name: "skills", desc: "list learned + installed skills" },
  { name: "skillify", arg: "[name]", desc: "distill this session into a draft SKILL.md (write_skill saves it — not auto-written)" },
  { name: "status", desc: "kernel, provider, keys, store health" },
  { name: "health", desc: "capability health — gmail/search/vision/browser/mcp + the exact fix for each gap" },
  { name: "world", arg: "[query]", desc: "view Vanta's world model — entities + relationships across your systems" },
  { name: "money", desc: "Money OS ledger — offers, prospect pipeline, revenue total" },
  { name: "radar", desc: "Opportunity radar — scored opportunities ranked by pain + buyer signal" },
  { name: "team", desc: "background worker roster — named agents, roles, status, blockers" },
  { name: "peers", desc: "live Vanta peer sessions on this machine (UDS) — id, title, pid for cross-session collab" },
  { name: "lifesearch", arg: "<query>", desc: "search across Vanta's local stores (world/money/radar/team/errors) — source-cited" },
  { name: "compartments", arg: "[path]", desc: "Vanta's self-repair body map — compartments + max autonomy per part" },
  { name: "skeptic", arg: "<claim>", desc: "adversarially verify a claim — refute by default, demand evidence" },
  { name: "security-review", arg: "[base]", desc: "security audit of the current branch's diff vs base (injection/secret/authz/traversal/exec/SSRF)" },
  { name: "locks", desc: "regression locks — verified behaviors + passing/regressed status (verification organ)" },
  { name: "nd", arg: "[<gate> on|off|<n>]", desc: "executive-function support gates — view/toggle/tune the ND gate set" },
  { name: "reach", desc: "internet-reach doctor — each channel's active backend + status + the exact fix per gap" },
  { name: "cookie", desc: "show login-walled reach channels with a stored cookie + the export guide" },
  { name: "goals", desc: "active goals from the kernel" },
  { name: "goal", arg: "<text|status|resume|clear|done N>", desc: "set / resume / drop a standing goal (a carried goal starts paused)" },
  { name: "plan", desc: "show the agent's current task plan (todo list)" },
  { name: "memory", arg: "<text>", desc: "tell Vanta something to remember (→ its brain)" },
  { name: "learnings", arg: "[list|add <kind>: <text>]", desc: "per-project learnings index — relevant insights, stale/conflicting flagged" },
  { name: "compress", desc: "compact the conversation context now" },
  { name: "compact", arg: "[instructions]", desc: "compact context now (alias of /compress; optional steer)" },
  { name: "sessions", desc: "list saved sessions" },
  { name: "resume", arg: "<id>", desc: "load a past session into this conversation" },
  { name: "title", arg: "<name>", desc: "name the current session" },
  { name: "fork", desc: "branch the current conversation into a new session" },
  { name: "cron", desc: "list scheduled tasks" },
  { name: "loop", arg: "<interval> <task>", desc: "schedule a recurring task from a natural-language interval (e.g. every 2 hours <task>, daily, every monday)" },
  { name: "proactive", desc: "proactive-autonomy mode (KAIROS) — whether idle ticking is enabled, the throttle, and would-it-tick-now (read-only)" },
  { name: "image", arg: "<path>", desc: "attach an image for your next message" },
  { name: "paste", desc: "attach an image from the clipboard (macOS)" },
  { name: "attachments", arg: "[clear]", desc: "show or clear pending image attachments" },
  { name: "branch", arg: "<name>", desc: "create or switch git branch (kernel-gated)" },
  { name: "context", desc: "visual context-budget breakdown" },
  { name: "files", desc: "list files in the current conversation context" },
  { name: "composer", arg: "<float|bottom>", desc: "input box position: float (default) or bottom-pinned" },
  { name: "vim", arg: "[on|off]", desc: "toggle vi-mode in the composer (normal/insert: hjkl, w/b, dd, yy, p, i/a/o)" },
  { name: "terminal-setup", desc: "print the steps to bind Shift+Enter → newline for your detected terminal (iTerm2/Apple Terminal/VS Code/WezTerm)" },
  { name: "cockpit", desc: "open mission-control — kernel verdict ladder, goals, loops (TUI)" },
  { name: "loops", desc: "live loops + escalations dashboard (TUI)" },
  { name: "changes", desc: "review changed files — per-file keep/undo (TUI)" },
  { name: "agents", desc: "background task panel — agent/shell/remote tasks, status, stop/respawn (TUI)" },
  { name: "mcp", desc: "MCP panel — servers + connection status, per-server tools, tool detail, reconnect (TUI)" },
  { name: "sandbox", desc: "sandbox settings — config, dependencies, doctor, per-tool overrides (TUI)" },
  { name: "permissions", arg: "[allow|ask|deny <tool> [pattern] | remove <n>]", desc: "tighten-only tool permission rules (~/.vanta/permissions.tsv)" },
  { name: "less-permission-prompts", desc: "scan the session for repeatedly-approved read-only tools and propose allow rules to cut future prompts (propose-only)" },
  { name: "reload-plugins", desc: "re-scan enabled plugins and load any added this session — reports newly available vs already loaded" },
  { name: "reload-skills", desc: "re-scan skill directories and pick up any added this session — reports added vs already-indexed vs removed" },
  { name: "preferences", arg: "export", desc: "export operator preference signals (~/.vanta/preferences.jsonl)" },
  { name: "usage", desc: "token usage + context fill for this session" },
  { name: "stats", desc: "aggregate usage — sessions, turns, tool calls, tokens/cost (TUI)" },
  { name: "copy", desc: "copy the last response to the clipboard" },
  { name: "update", desc: "git pull the latest Vanta (then ./install.sh to rebuild)" },
  { name: "moim", arg: "[text|clear]", desc: "pin a top-of-mind note injected into every prompt until cleared" },
  { name: "record", arg: "[start|stop]", desc: "record terminal output to an asciicast v2 .cast file under ~/.vanta/recordings" },
  { name: "output-style", arg: "<concise|normal|verbose>", desc: "control response verbosity" },
  { name: "ultrathink", arg: "<task>", desc: "deep-reasoning mode — plan, weigh tradeoffs + edge cases, then act" },
  { name: "ultracode", arg: "<task>", desc: "multi-agent coding push — decompose, parallel subagents, verify, synthesize" },
  { name: "deep-research", arg: "<question>", desc: "fan-out research — multi-source search, skeptic-verify, cited synthesis" },
  { name: "next", desc: "surface one concrete next micro-step from your active goals" },
  { name: "now", desc: "execute items in the Now column — agent picks up whatever you put there" },
  { name: "planmode", arg: "[on|off|approve]", desc: "enforced plan mode — write tools blocked until /planmode approve" },
  { name: "planv2", arg: "<task>", desc: "plan mode v2 — fan a task out across N concurrent plan-execution agents (VANTA_PLAN_V2_AGENT_COUNT, 1-10)" },
  { name: "tickets", desc: "issue board — first-class tickets grouped by status, with goal/parent links + inbox state" },
  { name: "outreach", desc: "authorized brand workspace — pending drafts + the proof ledger (draft-only, approval-gated)" },
  { name: "boundary", desc: "mark a task boundary — archive the current task state and begin fresh" },
  { name: "where", desc: "show last stated intent and recent tool call breadcrumb" },
  { name: "explain", arg: "[off]", desc: "capability-preservation surface — what changed + why, with a comprehension probe on risky/large changes" },
  { name: "recover", desc: "classify trouble — targeted bug, polluted context, or wrong assumption" },
  { name: "wm", arg: "[note]", desc: "view or add to session working memory (cleared each session)" },
  { name: "restart", desc: "reload Vanta in place with fresh code (needs ./run.sh)" },
  { name: "bug", arg: "<what happened>", desc: "record a structured bug with session + git context" },
  { name: "feedback", arg: "<text> | send", desc: "draft a redacted GitHub issue from feedback/feature requests; `send` files it" },
  { name: "handoff", desc: "copy-paste handoff packet (goals, git, files, next step)" },
  { name: "open", arg: "<file[:line]>", desc: "open a file:line in your editor ($VANTA_EDITOR/code)" },
  { name: "edit", desc: "edit the last AI response in your editor ($VANTA_EDITOR/code)" },
  { name: "tasks", arg: "[add|close|block|park|reopen|next]", desc: "operator task stack — /tasks next for the best move" },
  { name: "bgtasks", arg: "[stop <id>]", desc: "background shell tasks — list status, stop one by id" },
  { name: "wftasks", desc: "workflow run task list — compose_workflow runs + their running/done/failed status" },
  { name: "btw", arg: "<question>", desc: "ask a quick side question — not added to conversation history" },
  { name: "describe", arg: "<path>", desc: "generate a short LLM description of a file or directory" },
  { name: "diff", desc: "show uncommitted changes (working tree + staged)" },
  { name: "search", arg: "<query>", desc: "full-text search this session's transcript — ranked matches + highlighted snippets" },
  { name: "repro", desc: "save a diagnostic repro bundle to .vanta/repro-*.md" },
  { name: "summary", desc: "summarize this session (what was done, what remains)" },
  { name: "dashboard", desc: "live operator state — tasks, goals, repo, model" },
  { name: "brief", desc: "JARVIS-style today brief — tasks, goals, calendar, episodic" },
  { name: "review", arg: "[effort]", desc: "review changed code for bugs and cleanups (low|medium|high)" },
  { name: "simplify", desc: "reuse/simplify/efficiency/altitude pass on changed code" },
  { name: "auto", arg: "[lite|full|ultra|off|review]", desc: "auto-minimalism mode — do the least that works (stdlib>deps, deletion>addition); 'review' audits a diff for deletable code" },
  { name: "verify", desc: "run the app and confirm a change actually works" },
  { name: "run", desc: "launch and drive this project's app" },
  { name: "add-dir", arg: "<path>", desc: "add a directory to this session's readable/writable scope" },
  { name: "routes", desc: "show provider routing config (main + named VANTA_ROUTE_* overrides)" },
  { name: "rename", arg: "<name>", desc: "rename the current session" },
  { name: "tui", arg: "[fullscreen|status|exit]", desc: "TUI renderer info; /tui fullscreen confirms alt-screen mode" },
  { name: "focus", desc: "toggle focus view — hide tool events, show only user + final responses" },
  { name: "config", desc: "interactive settings — view + change config (TUI)" },
  { name: "settings", desc: "show/edit persisted settings" },
  { name: "models", desc: "list available models for the active provider" },
  { name: "lint", desc: "run the code-size gate on changed files" },
  { name: "roadmap", desc: "open the drag-and-drop roadmap board" },
  { name: "audit", desc: "run npm audit + dependency checks" },
  { name: "today", desc: "today brief — tasks, goals, calendar, episodic" },
  { name: "import", arg: "<archive.tgz>", desc: "import config/skills from a backup archive" },
  { name: "exit", desc: "leave the session" },
];

export const SLASH_HELP = [
  "  Commands:",
  ...SLASH_COMMANDS.map((c) => `    /${c.name}${c.arg ? ` ${c.arg}` : ""}`.padEnd(24) + c.desc),
  "",
  "  Prefixes (no slash needed):",
  "    ! <cmd>".padEnd(24) + "run a kernel-gated shell command inline",
  "    # <text>".padEnd(24) + "save a note to memory (brain → semantic region)",
  "",
  "  Anything else is sent to the agent (history persists across the session).",
].join("\n");

export function slashHelp(extra: ReadonlyArray<{ name: string; arg?: string; desc: string }> = []): string {
  if (!extra.length) return SLASH_HELP;
  return [
    "  Commands:",
    ...SLASH_COMMANDS.map((c) => `    /${c.name}${c.arg ? ` ${c.arg}` : ""}`.padEnd(24) + c.desc),
    "",
    "  Plugin commands:",
    ...extra.map((c) => `    /${c.name}${c.arg ? ` ${c.arg}` : ""}`.padEnd(24) + c.desc),
    "",
    "  Prefixes (no slash needed):",
    "    ! <cmd>".padEnd(24) + "run a kernel-gated shell command inline",
    "    # <text>".padEnd(24) + "save a note to memory (brain → semantic region)",
    "",
    "  Anything else is sent to the agent (history persists across the session).",
  ].join("\n");
}
