/** Canonical command catalog — drives `/help`, the TUI palette, and validation. */
export const SLASH_COMMANDS: ReadonlyArray<{ name: string; arg?: string; desc: string }> = [
  { name: "help", desc: "show this command list" },
  { name: "clear", desc: "start a fresh conversation (keeps the session log)" },
  { name: "reset", desc: "start a fresh conversation (alias of /clear)" },
  { name: "history", desc: "show this conversation's transcript" },
  { name: "export", desc: "export this conversation to a markdown file" },
  { name: "retry", desc: "re-run your last message" },
  { name: "undo", desc: "drop the last turn from the conversation" },
  { name: "model", desc: "change provider & model — interactive picker" },
  { name: "tools", desc: "list available tools" },
  { name: "skills", desc: "list learned + installed skills" },
  { name: "status", desc: "kernel, provider, keys, store health" },
  { name: "goals", desc: "active goals from the kernel" },
  { name: "goal", arg: "<text|status|clear|done N>", desc: "set / manage a standing goal Vanta works toward" },
  { name: "plan", desc: "show the agent's current task plan (todo list)" },
  { name: "memory", arg: "<text>", desc: "tell Vanta something to remember (→ its brain)" },
  { name: "compress", desc: "compact the conversation context now" },
  { name: "compact", arg: "[instructions]", desc: "compact context now (alias of /compress; optional steer)" },
  { name: "sessions", desc: "list saved sessions" },
  { name: "resume", arg: "<id>", desc: "load a past session into this conversation" },
  { name: "title", arg: "<name>", desc: "name the current session" },
  { name: "fork", desc: "branch the current conversation into a new session" },
  { name: "cron", desc: "list scheduled tasks" },
  { name: "image", arg: "<path>", desc: "attach an image for your next message" },
  { name: "paste", desc: "attach an image from the clipboard (macOS)" },
  { name: "attachments", arg: "[clear]", desc: "show or clear pending image attachments" },
  { name: "branch", arg: "<name>", desc: "create or switch git branch (kernel-gated)" },
  { name: "context", desc: "visual context-budget breakdown" },
  { name: "files", desc: "list files in the current conversation context" },
  { name: "theme", arg: "<name>", desc: "switch TUI color theme" },
  { name: "cockpit", desc: "open mission-control — kernel verdict ladder, goals, loops (TUI)" },
  { name: "mcp", desc: "list configured MCP servers" },
  { name: "permissions", arg: "[allow|ask|deny <tool> [pattern] | remove <n>]", desc: "tighten-only tool permission rules (~/.vanta/permissions.tsv)" },
  { name: "usage", desc: "token usage + context fill for this session" },
  { name: "copy", desc: "copy the last response to the clipboard" },
  { name: "update", desc: "git pull the latest Vanta (then ./install.sh to rebuild)" },
  { name: "moim", arg: "[text|clear]", desc: "pin a top-of-mind note injected into every prompt until cleared" },
  { name: "output-style", arg: "<concise|normal|verbose>", desc: "control response verbosity" },
  { name: "next", desc: "surface one concrete next micro-step from your active goals" },
  { name: "now", desc: "execute items in the Now column — agent picks up whatever you put there" },
  { name: "planmode", arg: "[on|off|approve]", desc: "enforced plan mode — write tools blocked until /planmode approve" },
  { name: "boundary", desc: "mark a task boundary — archive the current task state and begin fresh" },
  { name: "where", desc: "show last stated intent and recent tool call breadcrumb" },
  { name: "wm", arg: "[note]", desc: "view or add to session working memory (cleared each session)" },
  { name: "restart", desc: "reload Vanta in place with fresh code (needs ./run.sh)" },
  { name: "bug", arg: "<what happened>", desc: "record a structured bug with session + git context" },
  { name: "handoff", desc: "copy-paste handoff packet (goals, git, files, next step)" },
  { name: "open", arg: "<file[:line]>", desc: "open a file:line in your editor ($VANTA_EDITOR/code)" },
  { name: "edit", desc: "edit the last AI response in your editor ($VANTA_EDITOR/code)" },
  { name: "tasks", arg: "[add|close|block|park|reopen|next]", desc: "operator task stack — /tasks next for the best move" },
  { name: "btw", arg: "<question>", desc: "ask a quick side question — not added to conversation history" },
  { name: "diff", desc: "show uncommitted changes (working tree + staged)" },
  { name: "search", arg: "<query>", desc: "search conversation history for a term" },
  { name: "repro", desc: "save a diagnostic repro bundle to .vanta/repro-*.md" },
  { name: "summary", desc: "summarize this session (what was done, what remains)" },
  { name: "dashboard", desc: "live operator state — tasks, goals, repo, model" },
  { name: "brief", desc: "JARVIS-style today brief — tasks, goals, calendar, episodic" },
  { name: "review", arg: "[effort]", desc: "review changed code for bugs and cleanups (low|medium|high)" },
  { name: "simplify", desc: "reuse/simplify/efficiency/altitude pass on changed code" },
  { name: "verify", desc: "run the app and confirm a change actually works" },
  { name: "run", desc: "launch and drive this project's app" },
  { name: "add-dir", arg: "<path>", desc: "add a directory to this session's readable/writable scope" },
  { name: "routes", desc: "show provider routing config (main + named VANTA_ROUTE_* overrides)" },
  { name: "rename", arg: "<name>", desc: "rename the current session" },
  { name: "tui", arg: "[fullscreen|status|exit]", desc: "TUI renderer info; /tui fullscreen confirms alt-screen mode" },
  { name: "focus", desc: "toggle focus view — hide tool events, show only user + final responses" },
  { name: "exit", desc: "leave the session" },
];

export const SLASH_HELP = [
  "  Commands:",
  ...SLASH_COMMANDS.map((c) => `    /${c.name}${c.arg ? ` ${c.arg}` : ""}`.padEnd(24) + c.desc),
  "",
  "  Prefixes (no slash needed):",
  "    ! <cmd>".padEnd(24) + "run a kernel-gated shell command inline",
  "    # <text>".padEnd(24) + "save a note to memory (brain → semantic region)",
  "",
  "  Anything else is sent to the agent (history persists across the session).",
].join("\n");
