import { access, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import type { SlashHandler } from "./types.js";

type InitArgs = { force: boolean; print: boolean };

const MANIFESTS = ["package.json", "Cargo.toml", "pyproject.toml", "go.mod", "deno.json", "bun.lockb"];
const CONTEXT_FILES = ["AGENTS.md", "CLAUDE.md", "README.md", "ROADMAP.md"];
const SKIP_DIRS = new Set([".git", "node_modules", "target", "dist", "build", ".vanta", ".claude"]);

function parseInitArgs(arg: string): InitArgs | null {
  const parts = arg.split(/\s+/).filter(Boolean);
  if (parts.some((p) => !["--force", "--print"].includes(p))) return null;
  return { force: parts.includes("--force"), print: parts.includes("--print") };
}

async function exists(path: string): Promise<boolean> {
  return access(path).then(() => true, () => false);
}

async function firstLine(path: string): Promise<string> {
  const text = await readFile(path, "utf8").catch(() => "");
  return text.split(/\r?\n/).find((line) => line.trim())?.trim() ?? "";
}

async function detectStack(root: string): Promise<string[]> {
  const found = await Promise.all(MANIFESTS.map(async (m) => ((await exists(join(root, m))) ? m : "")));
  const lines = found.filter(Boolean).map((m) => `- ${m}`);
  if (await exists(join(root, "vanta-ts", "package.json"))) lines.push("- vanta-ts/package.json");
  return lines.length ? lines : ["- No common manifest detected"];
}

async function listStructure(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true }).catch(() => []);
  const visible = entries
    .filter((e) => !e.name.startsWith(".") && !SKIP_DIRS.has(e.name))
    .slice(0, 18)
    .map((e) => `- ${e.name}${e.isDirectory() ? "/" : ""}`);
  return visible.length ? visible : ["- (no visible files found)"];
}

async function contextHints(root: string): Promise<string[]> {
  const lines: string[] = [];
  for (const file of CONTEXT_FILES) {
    const line = await firstLine(join(root, file));
    if (line) lines.push(`- ${file}: ${line.replace(/^#\s*/, "")}`);
  }
  return lines.length ? lines : ["- No existing context docs detected"];
}

export async function buildInitDoc(root: string, now: Date): Promise<string> {
  const name = basename(root);
  const [stack, structure, hints] = await Promise.all([detectStack(root), listStructure(root), contextHints(root)]);
  return [
    `# CLAUDE.md — ${name}`,
    "",
    `Generated by Vanta /init on ${now.toISOString().slice(0, 10)}. Review and tighten this before relying on it as policy.`,
    "",
    "## Project",
    "",
    `- Root: ${root}`,
    "- Read existing `AGENTS.md` / `CLAUDE.md` files before editing nested folders.",
    "- Keep changes small, verified, and aligned with the repo's own safety rules.",
    "",
    "## Detected Stack",
    "",
    ...stack,
    "",
    "## Structure",
    "",
    ...structure,
    "",
    "## Existing Context",
    "",
    ...hints,
    "",
    "## Working Rules",
    "",
    "- Prefer existing commands from README/package manifests over inventing new workflows.",
    "- Run the narrowest useful test first, then broader verification before claiming completion.",
    "- Do not overwrite secrets or local config; keep generated files reviewable.",
    "",
  ].join("\n");
}

export const init: SlashHandler = async (arg, ctx) => {
  const opts = parseInitArgs(arg);
  if (!opts) return { output: "  usage: /init [--force] [--print]" };
  const root = dirname(ctx.dataDir);
  const out = join(root, ".claude", "CLAUDE.md");
  const body = await buildInitDoc(root, ctx.now());
  if (opts.print) return { output: body };
  if (!opts.force && await exists(out)) return { output: "  .claude/CLAUDE.md already exists — use /init --force to replace it" };
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, body, "utf8");
  return { output: `  · wrote ${out}` };
};
