import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { buildInitDoc, init } from "./init-cmd.js";
import type { ReplCtx } from "./types.js";

function ctx(root: string): ReplCtx {
  return {
    dataDir: join(root, ".vanta"),
    now: () => new Date("2026-06-14T12:00:00.000Z"),
    convo: { messages: [], send: async () => ({ finalText: "", iterations: 0, stoppedReason: "done", toolIterations: 0 }) },
    setup: {},
    state: { sessionId: "s", started: "t", turnIndex: 0 },
    env: {},
  } as unknown as ReplCtx;
}

describe("/init", () => {
  let root: string;

  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), "vanta-init-"));
    await writeFile(join(root, "package.json"), JSON.stringify({ scripts: { test: "vitest run" } }), "utf8");
    await writeFile(join(root, "AGENTS.md"), "# AGENTS.md — Example\n\nRules", "utf8");
    await mkdir(join(root, "src"));
    await writeFile(join(root, "src", "index.ts"), "export const ok = true;\n", "utf8");
  });

  afterEach(async () => {
    await rm(root, { recursive: true, force: true });
  });

  it("builds a project context document from detected files", async () => {
    const doc = await buildInitDoc(root, new Date("2026-06-14T12:00:00.000Z"));
    expect(doc).toContain("# CLAUDE.md");
    expect(doc).toContain("Generated by Vanta /init on 2026-06-14");
    expect(doc).toContain("- package.json");
    expect(doc).toContain("- src/");
    expect(doc).toContain("AGENTS.md: AGENTS.md — Example");
  });

  it("writes .claude/CLAUDE.md and refuses to overwrite by default", async () => {
    const first = await init("", ctx(root));
    expect(first.output).toContain(".claude/CLAUDE.md");
    const path = join(root, ".claude", "CLAUDE.md");
    expect(await readFile(path, "utf8")).toContain("Detected Stack");
    await writeFile(path, "custom", "utf8");
    const second = await init("", ctx(root));
    expect(second.output).toContain("already exists");
    expect(await readFile(path, "utf8")).toBe("custom");
  });

  it("supports --force and --print", async () => {
    const path = join(root, ".claude", "CLAUDE.md");
    await mkdir(join(root, ".claude"));
    await writeFile(path, "custom", "utf8");
    expect((await init("--print", ctx(root))).output).toContain("Working Rules");
    expect(await readFile(path, "utf8")).toBe("custom");
    expect((await init("--force", ctx(root))).output).toContain("wrote");
    expect(await readFile(path, "utf8")).toContain("Generated by Vanta /init");
  });

  it("reports usage for unknown flags", async () => {
    expect((await init("--bad", ctx(root))).output).toContain("usage:");
  });
});
